/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OtpPageRouteImport } from './routes/otp-page'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EditProfileRouteImport } from './routes/editProfile'
import { Route as CreateTopicRouteImport } from './routes/createTopic'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ChangeEmailRouteImport } from './routes/change-email'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicIdRouteImport } from './routes/topic/$id'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpPageRoute = OtpPageRouteImport.update({
  id: '/otp-page',
  path: '/otp-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/editProfile',
  path: '/editProfile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTopicRoute = CreateTopicRouteImport.update({
  id: '/createTopic',
  path: '/createTopic',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeEmailRoute = ChangeEmailRouteImport.update({
  id: '/change-email',
  path: '/change-email',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicIdRoute = TopicIdRouteImport.update({
  id: '/topic/$id',
  path: '/topic/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-email': typeof ChangeEmailRoute
  '/change-password': typeof ChangePasswordRoute
  '/createTopic': typeof CreateTopicRoute
  '/editProfile': typeof EditProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/otp-page': typeof OtpPageRoute
  '/profile': typeof ProfileRoute
  '/set-password': typeof SetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/success': typeof SuccessRoute
  '/topic/$id': typeof TopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-email': typeof ChangeEmailRoute
  '/change-password': typeof ChangePasswordRoute
  '/createTopic': typeof CreateTopicRoute
  '/editProfile': typeof EditProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/otp-page': typeof OtpPageRoute
  '/profile': typeof ProfileRoute
  '/set-password': typeof SetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/success': typeof SuccessRoute
  '/topic/$id': typeof TopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-email': typeof ChangeEmailRoute
  '/change-password': typeof ChangePasswordRoute
  '/createTopic': typeof CreateTopicRoute
  '/editProfile': typeof EditProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/otp-page': typeof OtpPageRoute
  '/profile': typeof ProfileRoute
  '/set-password': typeof SetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/success': typeof SuccessRoute
  '/topic/$id': typeof TopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-email'
    | '/change-password'
    | '/createTopic'
    | '/editProfile'
    | '/forgot-password'
    | '/otp-page'
    | '/profile'
    | '/set-password'
    | '/sign-in'
    | '/sign-up'
    | '/success'
    | '/topic/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-email'
    | '/change-password'
    | '/createTopic'
    | '/editProfile'
    | '/forgot-password'
    | '/otp-page'
    | '/profile'
    | '/set-password'
    | '/sign-in'
    | '/sign-up'
    | '/success'
    | '/topic/$id'
  id:
    | '__root__'
    | '/'
    | '/change-email'
    | '/change-password'
    | '/createTopic'
    | '/editProfile'
    | '/forgot-password'
    | '/otp-page'
    | '/profile'
    | '/set-password'
    | '/sign-in'
    | '/sign-up'
    | '/success'
    | '/topic/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangeEmailRoute: typeof ChangeEmailRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  CreateTopicRoute: typeof CreateTopicRoute
  EditProfileRoute: typeof EditProfileRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OtpPageRoute: typeof OtpPageRoute
  ProfileRoute: typeof ProfileRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SuccessRoute: typeof SuccessRoute
  TopicIdRoute: typeof TopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp-page': {
      id: '/otp-page'
      path: '/otp-page'
      fullPath: '/otp-page'
      preLoaderRoute: typeof OtpPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editProfile': {
      id: '/editProfile'
      path: '/editProfile'
      fullPath: '/editProfile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createTopic': {
      id: '/createTopic'
      path: '/createTopic'
      fullPath: '/createTopic'
      preLoaderRoute: typeof CreateTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-email': {
      id: '/change-email'
      path: '/change-email'
      fullPath: '/change-email'
      preLoaderRoute: typeof ChangeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$id': {
      id: '/topic/$id'
      path: '/topic/$id'
      fullPath: '/topic/$id'
      preLoaderRoute: typeof TopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangeEmailRoute: ChangeEmailRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  CreateTopicRoute: CreateTopicRoute,
  EditProfileRoute: EditProfileRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OtpPageRoute: OtpPageRoute,
  ProfileRoute: ProfileRoute,
  SetPasswordRoute: SetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SuccessRoute: SuccessRoute,
  TopicIdRoute: TopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
