import type { Topics } from 'prisma/generated/client'

export const MOCK_TOPICS: Topics[] = [
  {
    id: '1',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Present Simple',
    shortDescription: 'Learn how to use the Present Simple tense in English.',
    description:
      "The Present Simple tense is one of the most fundamental concepts in English grammar, primarily used to describe actions that are regular, habitual, or generally true. It's essential for talking about routines, schedules, and facts that don't change. For example, you use it to say 'The sun rises in the east' (a general truth) or 'I drink coffee every morning' (a habit). Understanding the Present Simple is the first step towards building a solid foundation in English and expressing everyday actions with clarity and confidence.",
    content: 'The Present Simple is used for habits, facts, and routines.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 25,
    userId: 'user-1',
    image: '/bg.png',
  },
  {
    id: '2',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Present Continuous',
    shortDescription: 'Understand the Present Continuous tense and its uses.',
    description:
      "The Present Continuous tense, also known as the Present Progressive, is used to describe actions that are happening at the exact moment of speaking, or actions that are in progress over a period of time. It's formed with the verb 'to be' (am, is, are) and the '-ing' form of the main verb. You would use it to say 'I am reading a book right now' or to talk about temporary situations like 'She is living in London for a few months.' It's also handy for describing future plans that have already been arranged, adding another layer of utility to this versatile tense.",
    content: 'The Present Continuous is used for actions happening now.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 18,
    userId: 'user-2',
    image: '/bg.png',
  },
  {
    id: '3',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Past Simple',
    shortDescription:
      'Master the Past Simple tense for talking about the past.',
    description:
      "The Past Simple tense is your go-to for talking about completed actions, events, or states in the past. If an action started and finished at a specific point in the past, you'll use the Past Simple. It's formed by adding '-ed' to regular verbs (e.g., 'walked', 'played') or by using the specific past form of irregular verbs (e.g., 'went', 'saw'). This tense is crucial for storytelling, recounting historical events, and sharing personal experiences that have already happened.",
    content: 'The Past Simple is used for completed actions in the past.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 22,
    userId: 'user-3',
    image: '/bg.png',
  },
  {
    id: '4',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Past Continuous',
    shortDescription: 'Learn when to use the Past Continuous tense.',
    description:
      'The Past Continuous tense is used to describe actions that were in progress at a specific time in the past. It is formed with was/were + verb-ing and often used to set the scene in stories or describe interrupted actions.',
    content: 'The Past Continuous is used for ongoing actions in the past.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 15,
    userId: 'user-4',
    image: '/bg.png',
  },
  {
    id: '5',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Present Perfect',
    shortDescription: 'Explore the Present Perfect tense and its uses.',
    description:
      "The Present Perfect tense is a bridge between the past and the present. It's used to talk about actions that happened at an unspecified time in the past but have a connection to the present moment. It's formed with 'have' or 'has' and the past participle of the main verb. For instance, 'I have lost my keys' implies that the keys are still lost now. It is also used to talk about life experiences, as in 'She has traveled to Japan.' Mastering the Present Perfect allows for more nuanced conversations about how past events affect the present.",
    content: 'The Present Perfect connects the past and the present.',
    level: 'Intermediate',
    duration: '30-45 minutes',
    likes: 30,
    userId: 'user-5',
    image: '/bg.png',
  },
  {
    id: '6',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Present Perfect Continuous',
    shortDescription: 'Understand the Present Perfect Continuous tense.',
    description:
      'The Present Perfect Continuous tense is used for actions that started in the past and continue to the present, or have recently stopped. It emphasizes the duration of the action and is formed with have/has been + verb-ing.',
    content: 'Used for actions that started in the past and continue now.',
    level: 'Intermediate',
    duration: '30-45 minutes',
    likes: 12,
    userId: 'user-6',
    image: '/bg.png',
  },
  {
    id: '7',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Past Perfect',
    shortDescription: 'Learn how to use the Past Perfect tense.',
    description:
      'The Past Perfect tense is used to show that one action was completed before another action in the past. It is formed with had + past participle and helps establish a clear sequence of past events.',
    content:
      'The Past Perfect is used for actions completed before another past action.',
    level: 'Intermediate',
    duration: '30-45 minutes',
    likes: 14,
    userId: 'user-7',
    image: '/bg.png',
  },
  {
    id: '8',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Past Perfect Continuous',
    shortDescription: 'Master the Past Perfect Continuous tense.',
    description:
      "The Past Perfect Continuous tense is used to talk about an ongoing action in the past that continued up until another past event. It focuses on the duration of the first action. It's formed with 'had been' and the '-ing' form of the verb. For example, 'She had been studying for hours before she finally took a break.' This tense is excellent for showing cause and effect in the past and for adding depth to your descriptions of past situations by emphasizing how long they lasted.",
    content: 'Used for actions that were ongoing up to a point in the past.',
    level: 'Intermediate',
    duration: '30-45 minutes',
    likes: 10,
    userId: 'user-8',
    image: '/bg.png',
  },
  {
    id: '9',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Future Simple',
    shortDescription: 'Learn how to talk about the future using Future Simple.',
    description:
      "The Future Simple tense is used to talk about things that we believe will happen in the future or to make spontaneous decisions. It is most commonly formed with the modal verb 'will' followed by the base form of the main verb. For example, 'I think it will rain tomorrow' is a prediction, while 'I'll have the salad' is a decision made at the moment of speaking. The Future Simple is a straightforward way to express future intentions, predictions, and promises.",
    content:
      'The Future Simple is used for predictions and decisions made at the moment.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 19,
    userId: 'user-9',
    image: '/bg.png',
  },
  {
    id: '10',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Future Continuous',
    shortDescription: 'Understand the Future Continuous tense.',
    description:
      "The Future Continuous tense describes an ongoing action that will be in progress at a specific time in the future. It helps to paint a picture of what will be happening at a particular future moment. It's formed with 'will be' and the '-ing' form of the verb. For example, 'This time next week, I will be relaxing on a beach.' It can also be used to ask politely about someone's plans: 'Will you be going to the party tonight?' This tense adds a sense of vividness to future descriptions.",
    content:
      'Used for actions that will be ongoing at a specific time in the future.',
    level: 'Intermediate',
    duration: '30-45 minutes',
    likes: 11,
    userId: 'user-10',
    image: '/bg.png',
  },
  {
    id: '11',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Future Perfect',
    shortDescription: 'Learn the Future Perfect tense.',
    description:
      "The Future Perfect tense is used to express an action that will be completed before a specific point in the future. It looks back from a future time to an earlier event. It is formed with 'will have' and the past participle of the verb. For example, 'By 2030, they will have finished building the bridge.' This tense is useful for setting deadlines and talking about accomplishments that are expected to be finalized by a certain future time, providing a clear endpoint for future actions.",
    content:
      'Used for actions that will be completed before a certain future time.',
    level: 'Intermediate',
    duration: '30-45 minutes',
    likes: 13,
    userId: 'user-11',
    image: '/bg.png',
  },
  {
    id: '12',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Future Perfect Continuous',
    shortDescription: 'Master the Future Perfect Continuous tense.',
    description:
      "The Future Perfect Continuous tense is used to emphasize the duration of an action up to a specific point in the future. It describes how long an action will have been happening by a certain future time. It's formed with 'will have been' and the '-ing' form of the verb. For example, 'In April, she will have been working here for ten years.' This advanced tense is perfect for situations where the length of a future ongoing activity is the main point of focus.",
    content:
      'Used for actions that will be ongoing up to a point in the future.',
    level: 'Advanced',
    duration: '30-45 minutes',
    likes: 7,
    userId: 'user-12',
    image: '/bg.png',
  },
  {
    id: '13',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Modal Verbs',
    shortDescription: 'Learn about modal verbs and their uses.',
    description:
      "Modal verbs are special auxiliary verbs that express concepts such as ability, permission, obligation, possibility, and advice. Common modal verbs include 'can', 'could', 'may', 'might', 'must', 'shall', 'should', 'will', and 'would'. They are different from normal verbs because they don't change form for person or tense. For example, 'She can swim' (ability) or 'You must finish your homework' (obligation). Understanding modal verbs is essential for expressing nuanced meanings and social functions in communication.",
    content:
      'Modal verbs express ability, possibility, permission, or obligation.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 21,
    userId: 'user-13',
    image: '/bg.png',
  },
  {
    id: '14',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Passive Voice',
    shortDescription: 'Understand how to use the passive voice.',
    description:
      "The passive voice is a grammatical construction where the subject of the sentence receives the action of the verb, rather than performing it. The focus shifts from the doer of the action to the action itself or the recipient. It is formed using the verb 'to be' and the past participle of the main verb. For example, in 'The ball was thrown by the boy,' the focus is on the ball. The passive voice is often used in formal and scientific writing, or when the agent is unknown or unimportant.",
    content:
      'The passive voice is used when the focus is on the action, not the subject.',
    level: 'Intermediate',
    duration: '30-45 minutes',
    likes: 17,
    userId: 'user-14',
    image: '/bg.png',
  },
  {
    id: '15',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Conditionals',
    shortDescription: 'Explore the different types of conditional sentences.',
    description:
      "Conditional sentences, also known as 'if clauses,' are used to talk about hypothetical situations and their consequences. There are several types, including the zero conditional (for general truths), the first conditional (for real future possibilities), the second conditional (for unreal present or future situations), and the third conditional (for unreal past situations). For example, 'If you heat water, it boils' (zero) vs. 'If I had known, I would have helped' (third). Mastering conditionals allows you to express a wide range of hypothetical scenarios.",
    content:
      'Conditionals are used to talk about possible or imaginary situations.',
    level: 'Intermediate',
    duration: '30-45 minutes',
    likes: 20,
    userId: 'user-15',
    image: '/bg.png',
  },
  {
    id: '16',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Reported Speech',
    shortDescription: 'Learn how to use reported speech.',
    description:
      "Reported speech, or indirect speech, is how we report what someone else has said without using their exact words. This often involves changes in tense, pronouns, and time/place adverbs. For example, the direct speech 'I am happy' becomes 'She said that she was happy' in reported speech. Learning the rules of reported speech is crucial for recounting conversations and integrating others' statements into your own narrative smoothly and accurately.",
    content: 'Reported speech is used to tell what someone else said.',
    level: 'Intermediate',
    duration: '30-45 minutes',
    likes: 16,
    userId: 'user-16',
    image: '/bg.png',
  },
  {
    id: '17',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Questions',
    shortDescription: 'Master forming questions in English.',
    description:
      "Forming questions correctly is a fundamental skill for communication. There are several types of questions in English, including 'yes/no' questions (e.g., 'Are you coming?'), 'wh-' questions that start with words like who, what, where, when, why, and how (e.g., 'Where do you live?'), and tag questions which are added to the end of a statement (e.g., 'It's a nice day, isn't it?'). Understanding the structure for each type will enable you to seek information effectively and engage in dynamic conversations.",
    content: 'Learn about yes/no questions, wh-questions, and question tags.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 23,
    userId: 'user-17',
    image: '/bg.png',
  },
  {
    id: '18',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Negatives',
    shortDescription: 'Learn how to form negative sentences.',
    description:
      "Forming negative sentences is essential for expressing denial, refusal, or the absence of something. In English, negatives are typically formed by adding 'not' after an auxiliary verb (like 'be', 'do', 'have') or a modal verb. For example, 'He is not here' or 'I do not like spinach.' Other negative words like 'never', 'no', 'nobody', and 'nothing' can also be used to create negative meaning. Correctly constructing negative sentences is key to clear and accurate communication.",
    content: 'Negatives are formed using not, never, nobody, etc.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 14,
    userId: 'user-18',
    image: '/bg.png',
  },
  {
    id: '19',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Articles',
    shortDescription: 'Understand the use of a, an, and the.',
    description:
      "Articles are small but powerful words that specify whether a noun is general or specific. 'A' and 'an' are indefinite articles used for non-specific nouns (e.g., 'a book'), while 'the' is the definite article used for specific nouns (e.g., 'the book on the table'). The choice between 'a' and 'an' depends on the sound of the following word. Mastering articles is one of the trickiest parts of learning English, but it is crucial for sounding natural and being understood correctly.",
    content: 'Articles are used to define nouns as specific or unspecific.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 27,
    userId: 'user-19',
    image: '/bg.png',
  },
  {
    id: '20',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Prepositions',
    shortDescription: 'Learn about prepositions of time, place, and movement.',
    description:
      "Prepositions are words like 'in', 'on', 'at', 'from', and 'to' that show the relationship between a noun or pronoun and other words in a sentence. They can indicate time ('at 5 PM'), place ('in the box'), and direction or movement ('to the store'). Prepositions are often tricky because their usage can be idiomatic and depends on context. A good understanding of prepositions is vital for constructing coherent sentences and expressing relationships between ideas, objects, and locations.",
    content: 'Prepositions show relationships between nouns and other words.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 22,
    userId: 'user-20',
    image: '/bg.png',
  },
  {
    id: '21',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Relative Clauses',
    shortDescription: 'Master the use of relative clauses.',
    description:
      "Relative clauses are used to add extra information about a noun in the main clause without starting a new sentence. They are introduced by relative pronouns like 'who', 'whom', 'whose', 'which', and 'that'. For example, in 'The man who lives next door is a doctor,' the relative clause 'who lives next door' identifies which man we are talking about. There are defining and non-defining relative clauses, and knowing the difference is key to providing either essential or additional information gracefully.",
    content: 'Relative clauses give more information about a noun.',
    level: 'Intermediate',
    duration: '30-45 minutes',
    likes: 12,
    userId: 'user-21',
    image: '/bg.png',
  },
  {
    id: '22',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Gerunds and Infinitives',
    shortDescription: 'Learn when to use gerunds and infinitives.',
    description:
      "Gerunds (the '-ing' form of a verb used as a noun, e.g., 'swimming is fun') and infinitives (the 'to' + base form of a verb, e.g., 'I want to swim') can be challenging for learners. The choice between using a gerund or an infinitive often depends on the main verb in the sentence. For example, you 'enjoy swimming' (gerund) but you 'decide to swim' (infinitive). Learning the patterns of which verbs are followed by which form is essential for grammatical accuracy and fluent expression.",
    content: 'Gerunds and infinitives are verb forms used after certain verbs.',
    level: 'Intermediate',
    duration: '30-45 minutes',
    likes: 15,
    userId: 'user-22',
    image: '/bg.png',
  },
  {
    id: '23',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Comparatives and Superlatives',
    shortDescription: 'Understand how to compare things in English.',
    description:
      "Comparatives and superlatives are forms of adjectives and adverbs used to compare two or more things. Comparatives (e.g., 'bigger', 'more interesting') are used to compare two items, while superlatives (e.g., 'biggest', 'most interesting') are used to compare three or more items and indicate the greatest degree. The rules for forming them depend on the number of syllables in the word. This is a fundamental area of grammar for making comparisons and expressing opinions.",
    content:
      'Comparatives and superlatives are used to compare two or more things.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 18,
    userId: 'user-23',
    image: '/bg.png',
  },
  {
    id: '24',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Countable and Uncountable Nouns',
    shortDescription:
      'Learn the difference between countable and uncountable nouns.',
    description:
      "In English, nouns can be either countable (things you can count, like 'one apple', 'two apples') or uncountable (things you can't count, like 'water', 'information'). This distinction is important because it affects which determiners (e.g., 'many' vs. 'much', 'few' vs. 'little') and articles you use, and whether the noun can be plural. Understanding this concept is key to avoiding common grammatical errors and constructing sentences correctly.",
    content: 'Some nouns can be counted, others cannot.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 13,
    userId: 'user-24',
    image: '/bg.png',
  },
  {
    id: '25',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Pronouns',
    shortDescription: 'Master the use of pronouns in English.',
    description:
      'Pronouns are words that take the place of nouns to avoid repetition. There are many types, including subject pronouns (I, you, he), object pronouns (me, you, him), possessive pronouns (mine, yours, his), and reflexive pronouns (myself, yourself, himself). Using the correct pronoun is essential for clear and concise writing and speech, as it ensures that the listener or reader knows who or what is being referred to at all times.',
    content: 'Pronouns replace nouns to avoid repetition.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 20,
    userId: 'user-25',
    image: '/bg.png',
  },
  {
    id: '26',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Adjectives and Adverbs',
    shortDescription: 'Learn the difference between adjectives and adverbs.',
    description:
      "Adjectives and adverbs are both describing words, but they modify different parts of a sentence. Adjectives describe nouns or pronouns (e.g., 'a beautiful day'), while adverbs describe verbs, adjectives, or other adverbs (e.g., 'she sings beautifully'). Understanding the difference and knowing where to place them in a sentence is crucial for adding detail and precision to your language, making your descriptions more vivid and your meaning clearer.",
    content:
      'Adjectives describe nouns, adverbs describe verbs, adjectives, or other adverbs.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 17,
    userId: 'user-26',
    image: '/bg.png',
  },
  {
    id: '27',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Word Order',
    shortDescription: 'Understand the typical word order in English sentences.',
    description:
      "English sentence structure typically follows a Subject-Verb-Object (SVO) word order. For example, 'The cat (S) chased (V) the mouse (O).' While this is the basic pattern, the order can change for questions, emphasis, or with the use of adverbs and other elements. Mastering the standard word order and its variations is fundamental to forming grammatically correct and natural-sounding sentences that are easy for others to understand.",
    content: 'English sentences usually follow the Subject-Verb-Object order.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 16,
    userId: 'user-27',
    image: '/bg.png',
  },
  {
    id: '28',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Phrasal Verbs',
    shortDescription: 'Explore common phrasal verbs and their meanings.',
    description:
      "Phrasal verbs are multi-word verbs made up of a main verb and a particle (a preposition or adverb), like 'look up' or 'get away'. The meaning of a phrasal verb is often idiomatic and cannot be guessed from the individual words. They are extremely common in everyday, informal English. Learning phrasal verbs is essential for understanding native speakers and for making your own speech sound more natural and fluent.",
    content: 'Phrasal verbs are verbs combined with prepositions or adverbs.',
    level: 'Intermediate',
    duration: '30-45 minutes',
    likes: 19,
    userId: 'user-28',
    image: '/bg.png',
  },
  {
    id: '29',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Direct and Indirect Objects',
    shortDescription: 'Learn about direct and indirect objects in sentences.',
    description:
      "In a sentence, the direct object is the noun or pronoun that directly receives the action of the verb. The indirect object is the recipient of the direct object. For example, in 'She gave me a book,' 'a book' is the direct object (what she gave) and 'me' is the indirect object (who she gave it to). Understanding the roles of direct and indirect objects helps you to analyze and construct more complex and varied sentence structures.",
    content: 'Objects receive the action of the verb in a sentence.',
    level: 'Intermediate',
    duration: '30-45 minutes',
    likes: 11,
    userId: 'user-29',
    image: '/bg.png',
  },
  {
    id: '30',
    createdAt: new Date(),
    updatedAt: new Date(),
    title: 'Interjections',
    shortDescription: 'Understand the use of interjections in English.',
    description:
      "Interjections are words or short phrases used to express sudden feelings or emotions. They are often set apart from the rest of the sentence by a comma or an exclamation mark. Examples include 'Wow!', 'Ouch!', 'Oh no!', and 'Well,'. While they are more common in informal speech and writing, they are a key part of expressing personality and emotion, making language more colorful and expressive.",
    content: 'Interjections are words used to express strong emotion.',
    level: 'Basic',
    duration: '30-45 minutes',
    likes: 9,
    userId: 'user-30',
    image: '/bg.png',
  },
]
